### PR TITLE
using websockets with arduino and esp8266

### PR DESCRIPTION
**Pull request by yashthipsay**
This is a PR for #9 for hacktoberfest 2023. It has the code for using websockets in arduino and esp8266

### CODE REVIEW

**Comment by Agnik7** [comment]
@yashthipsay This is a really great code!!!! I just have a simple request. Your fork is 2 commits behind this repo. Could you kindly rebase it? In your fork, you should see a button labeled as `Sync Fork`. Click on that button and then simply click on `Update branch`.

**Comment by yashthipsay** [comment]
> @yashthipsay This is a really great code!!!! I just have a simple request. Your fork is 2 commits behind this repo. Could you kindly rebase it? In your fork, you should see a button labeled as `Sync Fork`. Click on that button and then simply click on `Update branch`.

**Review by Agnik7 — APPROVED** [review]
Approved the changes. Merging it now.

**Comment by yashthipsay** [comment]
> @yashthipsay This is a really great code!!!! I just have a simple request. Your fork is 2 commits behind this repo. Could you kindly rebase it? In your fork, you should see a button labeled as `Sync Fork`. Click on that button and then simply click on `Update branch`.

I have updated my fork @Agnik7

**Pull request merged**
